name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: docker://rafaelcalleja/dind-buster:v0.1.8
      options: --privileged
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.updatev.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute next SemVer tag
        id: release
        run: |
          export VERSION=$(docker run --rm alpine/semver semver -c -i patch $(cat VERSION))
          echo $VERSION > VERSION
          echo ::debug ::relase version ${VERSION}
          echo ::set-output name=tag_name::v${VERSION}
      - name: Update version
        id: updatev
        run: |
           git config user.name  github-actions
           git config user.email github-actions@github.com
           git add VERSION
           git commit -m "bump version"
           git push
           echo ::set-output name=sha::$(git rev-parse --short HEAD)
           git rev-parse --symbolic-full-name --remotes=origin
  push:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_SHA: ${{needs.build.outputs.sha}}
        with:
          fetch-depth: 0
      - run: env
        env:
          GITHUB_SHA: ${{needs.build.outputs.sha}}
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{needs.build.outputs.tag_name}}"
          echo "Got Sha ${{needs.build.outputs.sha}}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_SHA: ${{needs.build.outputs.sha}}
        with:
          tag_name: ${{needs.build.outputs.tag_name}}
          release_name: Release ${{needs.build.outputs.tag_name}}
          body: |
            docker pull rafaelcalleja/keda-upstream-deployment-scaler:${{ steps.release.outputs.tag_name }}
          draft: false
          prerelease: false
          commitish: ${{needs.build.outputs.sha}}
