name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: docker://rafaelcalleja/dind-buster:v0.1.8
      options: --privileged
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.updatev.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute next SemVer tag
        id: release
        run: |
          export VERSION=$(docker run --rm alpine/semver semver -c -i patch $(cat VERSION))
          echo $VERSION > VERSION
          echo ::debug ::relase version ${VERSION}
          echo ::set-output name=tag_name::v${VERSION}
      - name: Update version
        id: updatev
        run: |
           git config user.name  github-actions
           git config user.email github-actions@github.com
           git add VERSION
           git commit -m "bump version"
           git push
           echo ::set-output name=sha::$(git rev-parse --short HEAD)
           git rev-parse --symbolic-full-name --remotes=origin
      - uses: passeidireto/trigger-external-workflow-action@main
        env:
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
          SHA: ${{ steps.updatev.outputs.sha }}
        with:
          repository: ${GITHUB_REPOSITORY}
          event: release_candidate
          github_pat: ${{ secrets.GITHUB_TOKEN }}
